---
# File: tasks/tls.yml - TLS tasks for vault
- name: Create SSL directory
  file:
    dest: "{{ vault_tls_dest_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- block:
  - name: create temporary directory
    command: "mktemp -d --suffix=.cert"
    register: temp_dir

  - debug:
      msg: "{{ temp_dir.stdout }}"
      verbosity: 2

# now create combined certificate
  - name: Copy certificate
    become: True
    copy:
      src: "{{ vault_tls_src_dir }}/{{ vault_tls_cert_file }}"
      dest: "{{ temp_dir.stdout }}/01.pem"

  - name: Copy CA certificate
    become: True
    copy:
      src: "{{ vault_tls_src_dir }}/{{ vault_tls_ca_file }}"
      dest: "{{ temp_dir.stdout }}/02.pem"

  - name: assemble certificate
    assemble:
      src: "{{ temp_dir.stdout }}"
      dest: "{{ vault_tls_dest_dir }}/{{ vault_tls_cert_file }}"

# single certificate
  - name: Copy CA certificate - seperate
    become: True
    copy:
      src: "{{ vault_tls_src_dir }}/{{ vault_tls_ca_file }}"
      dest: "{{ vault_tls_dest_dir }}/ca.pem"

# we must also enable trusting this ca on the server
# so vault cmd line client works correctly (without cert error)
  - name: copy CA certificate to trust root
    become: True
    copy:
      src: "{{ vault_tls_dest_dir }}/ca.pem"
      dest: "/usr/share/ca-certificates/cluster-ca.crt"
      remote_src: True

  - name: insert CA cert into trusted certs
    become: True
    lineinfile:
      path: /etc/ca-certificates.conf
      line: cluster-ca.crt

  - name: run update ca-certificates
    become: True
    command: /usr/sbin/update-ca-certificates

  #- name: Copy CA certificate
  #  become: True
  #  copy:
  #    src: "{{ vault_tls_src_dir }}/{{ vault_tls_ca_crt }}"
  #    dest: "{{ vault_tls_dest_dir }}/{{ vault_tls_ca_crt }}"
  #  notify:
  #  - reload vault
  #  - restart vault

  #- name: Copy certificate
  #  become: True
  #  copy:
  #    src: "{{ vault_tls_src_dir }}/{{ vault_tls_crt }}"
  #    dest: "{{ vault_tls_dest_dir }}/{{ vault_tls_crt }}.orig"
  #  notify:
  #  - reload vault
  #  - restart vault

  - name: Copy key
    become: True
    copy:
      src: "{{ vault_tls_src_dir }}/{{ vault_tls_key_file }}"
      dest: "{{ vault_tls_dest_dir }}/{{ vault_tls_key_file }}"
    notify:
    - restart vault

  when: vault_tls_disable == False

- block:
  - name: Copy CA certificate
    become: True
    copy:
      src: "{{ vault_tls_src_dir }}/{{ vault_config_consul_tls_ca_crt }}"
      dest: "{{ vault_tls_dest_dir }}/{{ vault_config_consul_tls_ca_crt }}"
    notify:
    - restart vault

  - name: Copy certificate
    become: True
    copy:
      src: "{{ vault_tls_src_dir }}/{{ vault_config_consul_tls_crt }}"
      dest: "{{ vault_tls_dest_dir }}/{{ vault_config_consul_tls_crt }}"
    notify:
    - restart vault

  - name: Copy key
    become: True
    copy:
      src: "{{ vault_tls_src_dir }}/{{ vault_config_consul_tls_key }}"
      dest: "{{ vault_tls_dest_dir }}/{{ vault_config_consul_tls_key }}"
    notify:
    - restart vault
